-- MySQL Script generated by MySQL Workbench
-- Thu Jun 18 00:12:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cena_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cena_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cena_db` DEFAULT CHARACTER SET latin1 ;
USE `cena_db` ;

-- -----------------------------------------------------
-- Table `cena_db`.`TB_CENA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cena_db`.`TB_CENA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cena` TEXT NOT NULL,
  `estado_cena` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cena_db`.`TB_CENA_ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cena_db`.`TB_CENA_ESTADO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_cena` TEXT NOT NULL,
  `dt_alteracao` DATETIME NOT NULL,
  `cena_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_TB_CENA_ESTADO_TB_CENA_IDX` (`cena_id` ASC) INVISIBLE,
  CONSTRAINT `FK_TB_CENA_ESTADO_TB_CENA`
    FOREIGN KEY (`cena_id`)
    REFERENCES `cena_db`.`TB_CENA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
